name: Validate Code

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [11.15]

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install --no-save
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm run lint
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm run lint:md
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
